In [1]:
import time
import copy

import numpy as np

import env
import vpg

In [2]:
game_spec = dict(
    n_players=2,
    n_territories=3,
    baseline_reinforcements=1,
    n_attacks_per_turn=1,
)

In [3]:
import torch
torch.manual_seed(0)
players = [vpg.VPGPlayer(0.01)] + [env.DumbPlayer() for i in range(game_spec['n_players'] - 1)]
env.play_games(game_spec, players, [0], verbose=True)

player=0, action=[0 3], board=[1. 0. 0. 5. 1. 0. 0. 2. 1. 0. 0. 6. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
player=1, action=[2 0], board=[0. 1. 0. 5. 1. 0. 0. 2. 1. 0. 0. 7. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
player=0, action=[0 5], board=[1. 0. 0. 4. 1. 0. 0. 2. 1. 0. 0. 7. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
player=1, action=[2 0], board=[0. 1. 0. 4. 1. 0. 0. 2. 1. 0. 0. 8. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
player=0, action=[0 0], board=[1. 0. 0. 3. 1. 0. 0. 2. 1. 0. 0. 8. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
player=1, action=[2 0], board=[0. 1. 0. 3. 1. 0. 0. 2. 1. 0. 0. 9. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
player=0, action=[0 1], board=[1. 0. 0. 2. 1. 0. 0. 2. 1. 0. 0. 9. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
player=1, action=[2 0], board=[ 0.  1.  0

(array([1], dtype=int32),
 array([[0., 1., 0., 1., 0., 1., 0., 8., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32),
 [])

In [4]:
from vpg import train_one_epoch
torch.manual_seed(0)
players = [vpg.VPGPlayer(0.01)] + [env.DumbPlayer() for i in range(game_spec['n_players'] - 1)]

out = vpg.train_one_epoch(game_spec, players, 629)

/home/tbent/.miniconda3/envs/rlrisk/lib/python3.9/site-packages/torch/autograd/__init__.py:145: UserWarning: CUDA initialization: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero. (Triggered internally at  /opt/conda/conda-bld/pytorch_1614378073166/work/c10/cuda/CUDAFunctions.cpp:109.)
  Variable._execution_engine.run_backward(


In [6]:
vpg.train(game_spec, players, 50, 1000, [0])

epoch: 0, player: 0, loss: 0.395 return: 0.656 ep_len: 39.177  n_games: 1000
epoch: 1, player: 0, loss: 0.410 return: 0.682 ep_len: 41.378  n_games: 1000
epoch: 2, player: 0, loss: 0.394 return: 0.668 ep_len: 40.669  n_games: 1000
epoch: 3, player: 0, loss: 0.378 return: 0.669 ep_len: 40.956  n_games: 1000
epoch: 4, player: 0, loss: 0.403 return: 0.673 ep_len: 39.558  n_games: 1000
epoch: 5, player: 0, loss: 0.403 return: 0.673 ep_len: 39.259  n_games: 1000
epoch: 6, player: 0, loss: 0.424 return: 0.703 ep_len: 38.388  n_games: 1000
epoch: 7, player: 0, loss: 0.449 return: 0.687 ep_len: 34.961  n_games: 1000
epoch: 8, player: 0, loss: 0.453 return: 0.683 ep_len: 33.480  n_games: 1000
epoch: 9, player: 0, loss: 0.495 return: 0.671 ep_len: 29.053  n_games: 1000
epoch: 10, player: 0, loss: 0.505 return: 0.692 ep_len: 26.520  n_games: 1000
epoch: 11, player: 0, loss: 0.459 return: 0.671 ep_len: 27.662  n_games: 1000
epoch: 12, player: 0, loss: 0.397 return: 0.678 ep_len: 31.206  n_games: 1

In [4]:
out = vpg.train_one_epoch(game_spec, players, 1)

/home/tbent/.miniconda3/envs/rlrisk/lib/python3.9/site-packages/torch/autograd/__init__.py:145: UserWarning: CUDA initialization: CUDA unknown error - this may be due to an incorrectly set up environment, e.g. changing env variable CUDA_VISIBLE_DEVICES after program start. Setting the available devices to be zero. (Triggered internally at  /opt/conda/conda-bld/pytorch_1614378073166/work/c10/cuda/CUDAFunctions.cpp:109.)
  Variable._execution_engine.run_backward(


In [5]:
out[3][0].actions[:2]

[3, 5]

In [6]:
out[3][0].obs[:2]

[array([1., 0., 0., 6., 0., 1., 0., 5., 1., 0., 0., 2., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32),
 array([1., 0., 0., 5., 0., 1., 0., 6., 1., 0., 0., 2., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)]

In [7]:
len(out[3][0].obs)

37

In [8]:
out[3][0].weights[:2]

[1.0, 1.0]

In [9]:
out[3][0].returns

[1.0]