In [1]:
import time
import copy

import numpy as np

from env import Env, DumbPlayer
from vpg import VPGPlayer, train

In [2]:
game_spec = dict(
    n_players=3,
    n_territories=8,
    baseline_reinforcements=3,
    n_attacks_per_turn=10,
)

In [3]:
env = Env(game_spec)
players = [VPGPlayer(env)] + [DumbPlayer() for i in range(game_spec['n_players'])]
nn_player_idx = 0

In [4]:
train(env, players, 50, 20000, [0])

/home/tbent/Dropbox/active/rlrisk/rlrisk/vpg.py:69: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /opt/conda/conda-bld/pytorch_1614378073166/work/torch/csrc/utils/tensor_numpy.cpp:143.)
  attack_to = self.get_action(torch.as_tensor(state_vec, dtype=torch.float32))


epoch: 0, player: 0, loss: 1.249 return: 0.617 ep_len: 248.160  n_games: 81
epoch: 1, player: 0, loss: 1.223 return: 0.625 ep_len: 229.932  n_games: 88
epoch: 2, player: 0, loss: 1.200 return: 0.706 ep_len: 237.035  n_games: 85
epoch: 3, player: 0, loss: 1.278 return: 0.744 ep_len: 223.144  n_games: 90
epoch: 4, player: 0, loss: 1.561 return: 0.864 ep_len: 227.386  n_games: 88
epoch: 5, player: 0, loss: 1.525 return: 0.851 ep_len: 230.782  n_games: 87
epoch: 6, player: 0, loss: 1.386 return: 0.833 ep_len: 225.833  n_games: 90
epoch: 7, player: 0, loss: 1.435 return: 0.874 ep_len: 230.506  n_games: 87
epoch: 8, player: 0, loss: 1.344 return: 0.854 ep_len: 244.488  n_games: 82
epoch: 9, player: 0, loss: 1.305 return: 0.833 ep_len: 258.154  n_games: 78
epoch: 10, player: 0, loss: 1.382 return: 0.871 ep_len: 286.529  n_games: 70
epoch: 11, player: 0, loss: 1.267 return: 0.844 ep_len: 262.805  n_games: 77
epoch: 12, player: 0, loss: 1.368 return: 0.912 ep_len: 299.735  n_games: 68
epoch: 13

In [5]:
selfplayer = copy.deepcopy(players[0])
selfplayers = [selfplayer] * 3
train(env, selfplayers, 20, 50000, [0,1,2])

epoch: 0, player: 0, loss: 0.302 return: 0.364 ep_len: 1206.023  n_games: 44
epoch: 0, player: 1, loss: 0.525 return: 0.295 ep_len: 642.886  n_games: 44
epoch: 0, player: 2, loss: 0.477 return: 0.341 ep_len: 983.295  n_games: 44
epoch: 1, player: 0, loss: 0.444 return: 0.526 ep_len: 1333.132  n_games: 38
epoch: 1, player: 1, loss: 0.460 return: 0.184 ep_len: 655.789  n_games: 38
epoch: 1, player: 2, loss: 0.301 return: 0.289 ep_len: 1107.553  n_games: 38
epoch: 2, player: 0, loss: 0.427 return: 0.512 ep_len: 1184.186  n_games: 43
epoch: 2, player: 1, loss: 0.460 return: 0.233 ep_len: 887.163  n_games: 43
epoch: 2, player: 2, loss: 0.312 return: 0.256 ep_len: 884.186  n_games: 43
epoch: 3, player: 0, loss: 0.294 return: 0.390 ep_len: 1227.829  n_games: 41
epoch: 3, player: 1, loss: 0.475 return: 0.268 ep_len: 712.927  n_games: 41
epoch: 3, player: 2, loss: 0.428 return: 0.341 ep_len: 993.878  n_games: 41
epoch: 4, player: 0, loss: 0.445 return: 0.523 ep_len: 1141.545  n_games: 44
epoch:

In [8]:
print(env.faceoff([players[0], DumbPlayer(), DumbPlayer()], 100)[1:])
print(env.faceoff([DumbPlayer(), players[0], DumbPlayer()], 100)[1:])
print(env.faceoff([DumbPlayer(), DumbPlayer(), players[0]], 100)[1:])

(array([0, 1, 2], dtype=int32), array([0.94, 0.04, 0.02]))
(array([0, 1], dtype=int32), array([0.08, 0.92]))
(array([0, 1, 2], dtype=int32), array([0.05, 0.02, 0.93]))


In [11]:
%%time
print(env.faceoff([selfplayer, DumbPlayer(), DumbPlayer()], 50)[1:])

(array([0, 1, 2], dtype=int32), array([0.54, 0.44, 0.02]))
CPU times: user 3.95 s, sys: 0 ns, total: 3.95 s
Wall time: 3.95 s


In [7]:
print(env.faceoff([selfplayer, DumbPlayer(), DumbPlayer()], 100)[1:])
print(env.faceoff([DumbPlayer(), selfplayer, DumbPlayer()], 100)[1:])
print(env.faceoff([DumbPlayer(), DumbPlayer(), selfplayer], 100)[1:])

(array([0, 1, 2], dtype=int32), array([0.92, 0.04, 0.04]))
(array([0, 1], dtype=int32), array([0.02, 0.98]))
(array([0, 1, 2], dtype=int32), array([0.08, 0.02, 0.9 ]))


In [9]:
print(env.faceoff([players[0], selfplayer, selfplayer], 100)[1:])
print(env.faceoff([selfplayer, players[0], selfplayer], 100)[1:])

(array([0, 1, 2], dtype=int32), array([0.51, 0.15, 0.34]))
(array([0, 1, 2], dtype=int32), array([0.48, 0.22, 0.3 ]))


In [6]:
faceoff([players[0], selfplayer, selfplayer], 100)[1:]

NameError: name 'faceoff' is not defined

In [16]:
faceoff([players[0], DumbPlayer(), DumbPlayer()], 10)

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32),
 array([0], dtype=int32),
 array([1.]))

In [ ]:
train(env, [DumbPlayer(), NNPlayer(), DumbPlayer()], 50, 1000)

In [ ]:
train(env, [DumbPlayer(), copy.deepcopy(players[0]), DumbPlayer()], 50, 1000)