In [2]:
import time
import copy

import numpy as np

from env import Env, DumbPlayer
from vpg import VPGPlayer, train

In [4]:
game_spec = dict(
    n_players=3,
    n_territories=8,
    baseline_reinforcements=3,
    n_attacks_per_turn=10,
)

In [5]:
env = Env(game_spec)
players = [VPGPlayer(env)] + [DumbPlayer() for i in range(game_spec['n_players'])]
nn_player_idx = 0

In [6]:
train(env, players, 50, 3000, [0])

/home/tbent/Dropbox/active/rlrisk/rlrisk/vpg.py:69: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /opt/conda/conda-bld/pytorch_1614378073166/work/torch/csrc/utils/tensor_numpy.cpp:143.)
  attack_to = self.get_action(torch.as_tensor(state_vec, dtype=torch.float32))


epoch: 0, player: 0, loss: 1.614 return: 0.857 ep_len: 222.714
epoch: 1, player: 0, loss: 0.378 return: 0.286 ep_len: 217.357
epoch: 2, player: 0, loss: 1.076 return: 0.385 ep_len: 241.615
epoch: 3, player: 0, loss: 1.309 return: 0.583 ep_len: 250.417
epoch: 4, player: 0, loss: 1.045 return: 0.467 ep_len: 205.200
epoch: 5, player: 0, loss: 0.650 return: 0.308 ep_len: 241.000
epoch: 6, player: 0, loss: 0.766 return: 0.385 ep_len: 241.846
epoch: 7, player: 0, loss: 1.530 return: 0.818 ep_len: 291.727
epoch: 8, player: 0, loss: 1.316 return: 0.667 ep_len: 365.444
epoch: 9, player: 0, loss: 1.284 return: 0.600 ep_len: 315.100
epoch: 10, player: 0, loss: 1.124 return: 0.500 ep_len: 421.125
epoch: 11, player: 0, loss: 1.157 return: 0.667 ep_len: 366.000
epoch: 12, player: 0, loss: 1.393 return: 0.833 ep_len: 507.000
epoch: 13, player: 0, loss: 1.173 return: 0.667 ep_len: 373.778
epoch: 14, player: 0, loss: 1.337 return: 0.700 ep_len: 362.000
epoch: 15, player: 0, loss: 1.178 return: 0.667 ep

In [10]:
print(env.faceoff([players[0], DumbPlayer(), DumbPlayer()], 100)[1:])
print(env.faceoff([DumbPlayer(), players[0], DumbPlayer()], 100)[1:])
print(env.faceoff([DumbPlayer(), DumbPlayer(), players[0]], 100)[1:])

(array([0, 1], dtype=int32), array([0.77, 0.23]))
(array([0, 1], dtype=int32), array([0.03, 0.97]))
(array([0, 1, 2], dtype=int32), array([0.06, 0.09, 0.85]))


In [5]:
selfplayer = copy.deepcopy(players[0])
selfplayers = [selfplayer] * 3
train(env, selfplayers, 10, 10000, [0,1,2])

epoch: 0, player: 0, loss: 0.372 return: 0.333 ep_len: 4872.333
epoch: 0, player: 1, loss: 0.162 return: 0.333 ep_len: 2645.333
epoch: 0, player: 2, loss: 0.746 return: 0.333 ep_len: 2848.000
epoch: 1, player: 0, loss: 0.531 return: 0.333 ep_len: 3596.333
epoch: 1, player: 1, loss: 0.875 return: 0.333 ep_len: 1419.667
epoch: 1, player: 2, loss: 0.148 return: 0.333 ep_len: 4199.667
epoch: 2, player: 0, loss: 0.341 return: 0.333 ep_len: 3942.333
epoch: 2, player: 1, loss: -0.000 return: 0.000 ep_len: 593.333
epoch: 2, player: 2, loss: 0.489 return: 0.667 ep_len: 3937.000
epoch: 3, player: 0, loss: 0.178 return: 0.250 ep_len: 2712.000
epoch: 3, player: 1, loss: 0.588 return: 0.250 ep_len: 937.750
epoch: 3, player: 2, loss: 0.395 return: 0.500 ep_len: 2994.750
epoch: 4, player: 0, loss: 0.799 return: 1.000 ep_len: 15087.000
epoch: 4, player: 1, loss: -0.000 return: 0.000 ep_len: 230.000
epoch: 4, player: 2, loss: -0.000 return: 0.000 ep_len: 15080.000
epoch: 5, player: 0, loss: 0.465 retur

In [11]:
print(faceoff(env, [selfplayer, DumbPlayer(), DumbPlayer()], 100)[1:])
print(faceoff(env, [DumbPlayer(), selfplayer, DumbPlayer()], 100)[1:])
print(faceoff(env, [DumbPlayer(), DumbPlayer(), selfplayer], 100)[1:])

(array([0, 1], dtype=int32), array([0.81, 0.19]))
(array([1], dtype=int32), array([1.]))
(array([0, 1, 2], dtype=int32), array([0.2 , 0.09, 0.71]))


In [6]:
faceoff([players[0], selfplayer, selfplayer], 100)[1:]

NameError: name 'faceoff' is not defined

In [16]:
faceoff([players[0], DumbPlayer(), DumbPlayer()], 10)

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32),
 array([0], dtype=int32),
 array([1.]))

In [ ]:
train(env, [DumbPlayer(), NNPlayer(), DumbPlayer()], 50, 1000)

In [ ]:
train(env, [DumbPlayer(), copy.deepcopy(players[0]), DumbPlayer()], 50, 1000)